import Head from 'next/head'
import { Footer } from '../components/footer/footer'
import { Header } from '../components/header/header'
import { EnterCard } from '../components/main/enter-card'
import { GoCard } from '../components/main/go-card'
import { HandbookCard } from '../components/main/handbook-card'
import { HelpCard } from '../components/main/help-card'
import { HistoryCard } from '../components/main/history-card'
import { VideoCard } from '../components/main/video-card'

export default function Home() {
  return (
    <div className="text-white">
      <Head>
        <title>Tiny Colony MVP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hidden lg:block"> 
        <Header />
        <main>
          <HistoryCard />
          <VideoCard />
          <HandbookCard />
          <EnterCard />
          <HelpCard/>
          <GoCard/>
        </main>
      </div>
      <div className="block lg:hidden"> 

      </div>
      <Footer />
    </div>
  )
}
