import Head from 'next/head'
import { Footer } from '../components/footer/footer'
import { Header } from '../components/header/header'
import { HistoryCard } from '../components/main/historyCard/historyCard'
import { VideoCard } from '../components/main/videoCard/videoCard'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="text-white">
      <Head>
        <title>Tiny Colony MVP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <HistoryCard />
        <VideoCard />
      </main>

      <Footer />
    </div>
  )
}
